import { GuideTableItem } from "@/types/Guide";

export const items: GuideTableItem[] = [
  {
    title: "Aire Ancient Baths",
    location: "https://maps.app.goo.gl/LTNxRGoMnzFM4wKU6",
    link: "https://relax.beaire.com/aire-ancient-baths-barcelona",
    price: "€100+",
    type: "Fun",
    description: "Thermal baths and spa experience in the old city.",
  },
  {
    title: "Aquarium de Barcelona",
    location: "https://maps.app.goo.gl/ecv77Rp9SeWuUobn7",
    link: "https://tickets.aquariumbcn.com/",
    price: "€14",
    type: "Fun",
    description: "Large aquarium with Mediterranean and tropical marine life.",
  },
  {
    title: "Axe Throwing",
    location: "https://maps.app.goo.gl/VpaFan2JHpS9A97P7",
    link: "https://barcelonaaxethrowing.com/",
    price: "€19.50",
    type: "Activity",
    description: "Indoor axe-throwing games in the city centre.",
  },
  {
    title: "Basílica del Sagrat Cor Tibidabo",
    type: "Place",
    location: "https://maps.app.goo.gl/wfmdK47p23poZLVM7",
    link: "https://tibidabo.salesianos.edu/",
  },
  {
    title: "Barcelona Botanical Garden",
    type: "Place",
    price: "€5",
    location: "https://maps.app.goo.gl/kQ7AxvQUmq1jDRJ58",
    link: "https://museuciencies.cat/en/the-nat/venues/botanical-garden-of-barcelona",
    tags: ["Free 1st Sunday"],
    description:
      "Mediterranean plant garden; visit La Caseta del Migdia afterwards for sunrise.",
  },
  {
    title: "Barcelona Zoo",
    price: "€21.40",
    location: "https://maps.app.goo.gl/Y33ARACBXcY2unwV8",
    link: "https://zoobarcelona.cat/en/home",
    type: "Fun",
    description:
      "Mid-sized city zoo with a wide variety of animals in Parc de la Ciutadella including komodo dragons, hippos, giraffes, hyenas, elephants, lions, red pandas, penguins, orangutans",
  },
  {
    title: "Bewake Park",
    price: "€39 / 2 hours",
    location: "https://maps.app.goo.gl/WPjEWuqFtC3Luv6j8",
    link: "https://bewakepark.com/",
    type: "Activity",
    description: "Cable wakeboarding and water sports park.",
  },
  {
    title: "Biblioteca Gabriel García Márquez",
    price: "Free",
    location: "https://maps.app.goo.gl/Rg4cM3gsk8U9QCEx5",
    link: "https://ajuntament.barcelona.cat/biblioteques/ca/bibgarciamarquez",
    type: "Place",
    description:
      "Public library designed by SUMA Arquitectura, and uses exposed wood and glass, creating a warm, modern environment. There’s a special comic section showcasing works by Francisco Ibáñez, a local comic artist, with a collection of 500 pieces.",
  },
  {
    title: "Bungee Jump",
    price: "€60 / 2 jumps",
    location: "https://maps.app.goo.gl/nDh9mxgyLUZZCtTa9",
    link: "https://www.cataloniaadventures.com/puenting-catalunya/",
    type: "Activity",
    tags: ["Day Trip"],
    description:
      "Outdoor bungee jumping experience 130km outside of Barcelona. Experience a 30 meter jump above the river canyon, with a pendulum effect of up to 25 meters.",
  },
  {
    title: "Bunkers del Carmel",
    price: "Free",
    location: "https://maps.app.goo.gl/WiNPByzatAMXYZyp6",
    link: "https://www.barcelona.cat/museuhistoria/ca/patrimonis/els-espais-del-museu/turo-de-la-rovira",
    type: "Place",
    description:
      "MUHBA Turó de la Rovira offers panoramic views of Barcelona from Spanish Civil War bunkers where anti-aircraft guns were installed.",
  },
  {
    title: "CaixaForum",
    price: "€6",
    type: "Place",
    location: "https://maps.app.goo.gl/AhiX6L9Lnt35ARC56",
    link: "https://caixaforum.org/es/barcelona",
    description: "Cultural centre with art exhibitions and events.",
  },
  {
    title: "Ceramics & Wine",
    price: "€25",
    link: "https://www.groupon.es/deals/tiwona-taller-de-ceramica-barcelona-workshops-coworking",
    location: "https://maps.app.goo.gl/HtMyDm8yrf96TjWcA",
    type: "Fun",
    description: "Pottery workshop combined with wine tasting.",
  },
  {
    title: "Montjuïc Cable Car",
    price: "€10.80",
    type: "Activity",
    link: "https://www.telefericdemontjuic.cat/en",
    location: "https://maps.app.goo.gl/Be5ypmRLntBPeqxE7",
    description: "Scenic cable car ride up to Montjuïc Hill.",
  },
  {
    title: "Ciutadella Park",
    location: "https://maps.app.goo.gl/3zbVCi4pDm6Ft3Gh8",
    link: "https://www.barcelona.cat/es/que-hacer-en-bcn/parques-y-jardines/parque-de-la-ciutadella-92086011921",
    type: "Place",
  },
  {
    title: "CosmoCaixa Museum of Science",
    type: "Place",
    price: "€8",
    location: "Carrer d'Isaac Newton, 26, Sarrià-Sant Gervasi, 08022 Barcelona",
    link: "https://maps.app.goo.gl/Fdvn6xJkaYZ5M7RA8",
    description:
      "Interactive science museum with exhibitions and a planetarium.",
  },
  {
    title: "The Comedy Clubhouse",
    type: "Fun",
    price: "Free - €20",
    link: "https://thecomedyclubhouse.es/",
    location: "https://maps.app.goo.gl/FyTwtgb4B9auaqaX9",
    description:
      "Stand-up comedy venue with regular shows in English and Spanish.",
  },
  {
    title: "Museu del Disseny de Barcelona",
    price: "€6.20",
    tags: ["Free 1st Sunday"],
    location: "https://maps.app.goo.gl/v6bfWM5D4TCVVaRY6",
    link: "https://www.dissenyhub.barcelona/",
    type: "Place",
    description: "Museum dedicated to design, fashion, and decorative arts.",
  },
  {
    title: "Dr. Flow Bar",
    location: "https://maps.app.goo.gl/49Gq84m8dkRWd59n7",
    link: "https://www.drflow.es/programacion/",
    type: "Music",
    description: "Live music venue located in El Born.",
  },
  {
    title: "Flamenco theater - Palau Dalmases",
    type: "Fun",
    price: "€30",
    link: "https://www.flamencopalaudalmases.com/",
    location: "https://maps.app.goo.gl/H3R6B8XBU1hRH6mw7",
    description: "Traditional Spanish dance and music performance.",
  },
  {
    title: "Flotarium",
    price: "€75 for 2",
    link: "https://www.flotarium.com/tienda/",
    location: "https://maps.app.goo.gl/FJ1cQd61qpTZYkYQ9",
    type: "Fun",
    description: "Sensory deprivation floatation tank experience.",
  },
  {
    title: "Fundació Joan Miró",
    price: "€9",
    location: "https://maps.app.goo.gl/WK2VEt35TScS8K7x7",
    link: "https://www.fmirobcn.org/",
    type: "Fun",
    description:
      "Showcase of Joan Miro's modern, colorful artworks in hilltop museum with courtyards and terraces.",
  },
  {
    title: "Mirador Torre Glòries",
    price: "€18",
    type: "Place",
    location: "https://maps.app.goo.gl/Cuf9cmmt91Duf1Sq9",
    link: "https://www.miradortorreglories.com/planifica-tu-visita/comprar-entradas/",
    description: "Modern skyscraper also known as Torre Glòries.",
  },
  {
    title: "Jazz at 23 Robadors",
    price: "€8",
    type: "Fun",
    link: "https://23robadors.com/programacio/",
    location: "https://maps.app.goo.gl/Y1MtCGiLZxJQAPEv9",
    description: "Intimate bar offering live jazz music.",
  },
  {
    title: "Parc del Laberint d'Horta",
    price: "€2.23",
    type: "Place",
    link: "https://guia.barcelona.cat/en/detall/parc-del-laberint-d-horta_92086011952.html",
    location: "https://maps.app.goo.gl/9BhXR3c49gvMNje76",
    description: "Historical garden with a maze and romantic architecture.",
  },
  {
    title: "MACBA",
    type: "Activity",
    price: "€10,80",
    link: "https://www.macba.cat",
    tags: ["Free after Saturday 4pm"],
    location: "https://maps.app.goo.gl/NgbAxXmbCPiVDJFRA",
    description:
      "Museu d'Art Contemporani de Barcelona has built a collection of over 5,000 works, concentrating on post-1945 Catalan and Spanish art, while also including international pieces.",
  },
  {
    title: "Castell de Montjuïc",
    tags: ["Free 1st Sunday"],
    price: "€12",
    type: "Place",
    link: "https://ajuntament.barcelona.cat/castelldemontjuic/en/visit/planning-your-visit",
    location: "https://maps.app.goo.gl/TDYFQHaGyGyoCkk78",
    description: "Historic fortress with city views at the top of Montjuïc.",
  },
  {
    title: "Museu Nacional d'Art de Catalunya",
    price: "€12",
    type: "Place",
    location: "https://maps.app.goo.gl/z2jAgAz1KuYa2nULA",
    link: "https://www.mnac.cat/",
    tags: ["Free 1st Sunday", "Free after Saturday 3pm"],
  },
  {
    title: "Nau Bostik",
    type: "Place",
    location: "https://maps.app.goo.gl/Bky7avBMcoKVwuTv9",
    link: "https://naubostik.com/",
  },
  {
    title: "Observatori Fabra de Barcelona",
    tags: ["Free 1st Sunday", "Free every Sunday 11am", "Cash only"],
    price: "€3",
    type: "Place",
    description:
      "Historic astronomical observatory offering tours and stargazing.",
    link: "https://observatorifabra.cat/visits/",
    location: "https://maps.app.goo.gl/mQgU3BMHx2kojxEx6",
  },
  {
    title: "Observatori Fabra - Night guided tour",
    price: "€18.50 - €30",
    type: "Place",
    description:
      "Every Friday and Saturday between October to May you will have the opportunity to visit the Fabra Observatory, enjoy a conference and the views of Barcelona from the outside of the dome and see the stars through the telescope.",
    link: "https://www.sternalia.com/en/guided-tours-fabra-observatory.html",
    location: "https://maps.app.goo.gl/mQgU3BMHx2kojxEx6",
  },
  {
    title: "Observatori Fabra - Dinner with stars",
    link: "https://www.sternalia.com/en/dinners-with-stars.html",
    location: "https://maps.app.goo.gl/mQgU3BMHx2kojxEx6",
    price: "€81.50 - €128",
    type: "Activity",
  },
  {
    title: "Padel",
    location: "App Dependant",
    link: "https://playtomic.com/",
    price: "€7 - €20",
    type: "Activity",
    description:
      "Book and play padel matches with strangers or friends using the Playtomic app.",
  },
  {
    title: "CeleBreak",
    location: "App Dependant",
    link: "https://celebreak.com/es/",
    price: "€7 - €20",
    type: "Activity",
    description:
      "Book and play soccer matches with strangers or friends using the CeleBreak app.",
  },
  {
    title: "Palau Martorell",
    type: "Place",
    location: "https://maps.app.goo.gl/jrAQMgSNdveGvyKS7",
    link: "https://www.palaumartorell.com/en/visita",
    price: "€16",
    description: "Exhibition hall hosting art and cultural events.",
  },
  {
    title: "Palo Alto",
    type: "Fun",
    location: "https://maps.app.goo.gl/SLVni93PmeVEJxtY6",
    link: "https://www.paloalto.barcelona/esdeveniments",
  },
  {
    title: "Razzmatazz",
    type: "Music",
    location: "https://maps.app.goo.gl/QfjV8VvyudB7nnPn9",
    link: "https://www.salarazzmatazz.com",
    price: "€10 - €20",
    description: "Large music venue and nightclub in Poble Nou.",
  },
  {
    title: "Recinte Modernista de Sant Pau",
    location: "https://maps.app.goo.gl/grFnrFHZ1tM74f5v6",
    link: "https://santpaubarcelona.org/en/visita/visita-lliure/",
    price: "€11.90",
    type: "Place",
    description: "Modernist hospital complex and UNESCO World Heritage site.",
  },
  {
    title: "Rouge Cocktail Club",
    location: "https://maps.app.goo.gl/7Un6zEftLsCZEMyAA",
    link: "https://www.instagram.com/rouge_cocktailclub/",
    type: "Music",
    description: "Live music bar in Poble Sec.",
  },
  {
    title: "SABDA",
    type: "Fun",
    description:
      "Immersive yoga, pilates, breathwork, and more in tranquil space with spatial audio and 360° visuals.",
    location: "https://maps.app.goo.gl/6vbcKFMdCctZx6Ls9",
    link: "https://sabda.es/classes/",
    price: "€20",
  },
  {
    title: "Sagrada Familia",
    price: "€31.80",
    type: "Place",
    description: "Gaudí's world-famous unfinished basilica.",
    location: "https://maps.app.goo.gl/qgsz87obhV6R9Hre7",
    link: "https://ticketsagradafamilia.com/",
  },
  {
    title: "Sailing Experience Barcelona",
    location: "https://maps.app.goo.gl/DrDdKV3uPbUPUzg26",
    link: "https://www.instagram.com/sailingexperiencebarcelona/",
    type: "Activity",
    description: "Guided sailing trips along Barcelona's coast.",
  },
  {
    title: "Sala Apolo",
    location: "https://maps.app.goo.gl/1pe6KwRWYhSqRdqb6",
    link: "https://sala-apolo.com/es/agenda",
    type: "Music",
    description: "Popular concert hall and nightclub.",
  },
  {
    title: "Sala Upload",
    link: "https://sala-upload.com/",
    location: "https://maps.app.goo.gl/drGuWcRZFZn3tYEY9",
    type: "Music",
    description: "Live music venue in Montjuïc.",
  },
  {
    title: "Shark Diving",
    location: "https://maps.app.goo.gl/ecv77Rp9SeWuUobn7",
    price: "€300",
    link: "https://tickets-actividades.aquariumbcn.com/pass/1137305161",
    type: "Fun",
    description: "Dive with sharks at the Barcelona Aquarium.",
  },
  {
    title: "Skydiving",
    price: "€300",
    link: "https://saltamos.es/en/tandem-jump/",
    location: "https://maps.app.goo.gl/ToycpFwpXmxCbzqc8",
    type: "Activity",
    description: "Tandem parachute jump experience near Barcelona.",
  },
  {
    title: "Sala Taro",
    location: "https://maps.app.goo.gl/5znMc89VHdpCjNR26",
    link: "https://dice.fm/venue/sala-taro-lv8x",
    type: "Music",
    description: "Late night venue & bar in Sants.",
  },
  {
    title: "Teatre Grec",
    type: "Place",
    location: "https://maps.app.goo.gl/xfbZv7BCyDtfdWbh6",
    link: "https://www.barcelona.cat/grec/es",
    price: "Free",
  },
  {
    title: "Tibidabo Ice Rink",
    tags: ["Winter"],
    type: "Activity",
    description: "Seasonal outdoor ice-skating rink at Tibidabo.",
    link: "https://tibidabo.cat/en/events/ice-rink",
    location: "https://maps.app.goo.gl/VBNxWxDVfqHvUnTH7",
  },
  {
    title: "White Rabbit Museum",
    price: "€15",
    type: "Place",
    description: "Museum showcasing contemporary art.",
    location: "https://maps.app.goo.gl/h5R6FTSrwzbnAkhg7",
    link: "https://tickets.whiterabbit-theoffmuseum.com/en-ES/1283/7951?s=maps&f=nav&lang=en-ES",
  },
  {
    title: "Trip to Montserrat Abbey",
    type: "Place",
    location: "https://maps.app.goo.gl/5HpFHD5TyVWSXmVE9",
    link: "https://tickets.montserratvisita.com",
    description:
      "Take a train to Monistrol de Montserrat and get a Cremallera to the abbey, and witness the best views of the surroundings. Getting the ticket to enter the Abbey is definitely optional.",
  },
  {
    title: "Centre Cívic Convent de Sant Agustí",
    type: "Place",
    location: "https://maps.app.goo.gl/oYJfoYAucbqdjnGF8",
    link: "https://conventagusti.com/",
    price: "Free",
  },
];
